// /decks/lib — librería de motion + sistema de diseño compartida por los 4 decks (decks-brief-v2 Parte 1)
export { gsap, T, EASE, ease, sec } from './motion/ease.js'
export { Stagger } from './motion/stagger.js'
export { Parallax } from './motion/parallax.js'
export { Flipbook } from './motion/flipbook.js'
export { KineticType } from './motion/kinetic-type.js'
export { FlapDigits } from './motion/flap-digits.js'
export { Streaks } from './motion/streaks.js'
export { Grain } from './motion/grain.js'
export { Cursor } from './motion/cursor.js'
export { Transition } from './motion/transition.js'
export { SoundBus } from './motion/sound-bus.js'
export { ContactShadow } from './motion/contact-shadow.js'
export { createDeck } from './deck.js'
export { createAssets } from './assets.js'
export { placeholder, registerPlaceholder } from './placeholder.js'
export * from './util/dom.js'
export * from './util/prng.js'
